using ExactDiag
using LinearAlgebra
x1 = Vector{Float64}()
x2 = Vector{Float64}()
x3 = Vector{Float64}()
x4 = Vector{Float64}()
y1 = Vector{Float64}()
y2 = Vector{Float64}()
y3 = Vector{Float64}()
y4 = Vector{Float64}()
for L in 3:7
  init(2, L)
  hj = sqrt(1.5)
  vj = sqrt(2.0)
  Δ = sqrt(1.3)
  kj = sqrt(2.5)
  H1 = sum(j -> spin('z', j) * spin('z', j + 1), 1) - sum(j -> hj * spin('x', j)) - sum(j -> vj * spin('z', j))
  H2 = sum(j -> spin('x', j) * spin('x', j + 1) + spin('y', j) * spin('y', j + 1) + Δ * spin('z', j) * spin('z', j + 1), 1) - sum(j -> hj * spin('x', j)) - sum(j -> vj * spin('z', j))
  _, energy1, _ = block_diag1(H1, site_flip(), true)
  _, energy2, _ = block_diag1(H2, site_flip(), true)
  println("L = ", L)
  println(energy_degeneracy_check(energy1[1]))
  println(energy_degeneracy_check(energy1[2]))
  println(energy_degeneracy_check(energy2[1]))
  println(energy_degeneracy_check(energy2[2]))
end